"""add archaic genome data index

Revision ID: f5cb2571a2a4
Revises: 6c8442b2dd91
Create Date: 2018-09-11 14:07:46.183714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5cb2571a2a4'
down_revision = '6c8442b2dd91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_sample_run', 'archaic_genome_data', ['sample_id', 'archaic_analysis_run_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_sample_run', table_name='archaic_genome_data')
    # ### end Alembic commands ###
